name: Firecrawl Python

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          FIRECRAWL_API: ${{ secrets.FIRECRAWL_API }}
